Refactor reducers sagas
coopify/coopify-frontend pull request #46
Opened 2019-07-04 01:03 UTC by ismaelpuricelli

2019-07-04 23:28 UTC, agustico13 approved these changes

2019-07-05 16:14 UTC, CamiloNicolasMartinez commented on src/components/conversations.jsx
> +  error: state.conversation.error,
Error y loading pq estan a nivel de conversation cuando son cosas genericas?

2019-07-05 16:15 UTC, CamiloNicolasMartinez commented on src/components/coopiesAccount.jsx
> +  loggedUser: state.user.user,
Pq tenemos un `State.user.user`??

2019-07-05 16:40 UTC, CamiloNicolasMartinez requested changes
Si bien estamos mejorando, tengo la sensación que podemos mejorar un poco más con respecto a las transformaciones que hacemos sobre el state. El usuario al loguearse deberia de sobre escribir todo el objeto user, no solo el q está dentro del user.user. Debemos de mejorar eso cambiando el nombre del primer user o manejando bien de una eso.

2019-07-06 22:18 UTC, ismaelpuricelli commented on src/components/coopiesAccount.jsx
> +  loggedUser: state.user.user,
Eso es porque cuando dividimos los reducers le agrega el nombre del reducer como objeto, es decir, el primer `user` es el nombre de `UserReducer `y el segundo es el objeto `user `que tiene al usuario logueado.

2019-07-07 15:22 UTC, juan17rodriguez approved these changes

2019-07-08 15:42 UTC, juan17rodriguez approved these changes

2019-07-08 18:38 UTC, agustico13 approved these changes

2019-07-08 18:44 UTC, CamiloNicolasMartinez approved these changes

2019-07-08 22:11 UTC, merged