Login form usability
coopify/coopify-frontend pull request #47
Opened 2019-07-04 01:32 UTC by ismaelpuricelli

2019-07-04 23:31 UTC, agustico13 approved these changes

2019-07-05 16:44 UTC, CamiloNicolasMartinez commented on src/components/conversations.jsx
>            <LoadingScreen
Esto es una clara demostración de que no estamos declarando nuestros componentes de manera única. El loading debería de ser un único componente al que se llama de todos estos lados. Uno de los beneficios de esto seria q tenemos que tener el color en un único lugar sin tener que andar cambiando la config en cada uno de ellos. Ademas que evitamos meter cosas inecesarias en el Global.

2019-07-05 16:45 UTC, CamiloNicolasMartinez requested changes
Creo q se puede aprovechar esta oportunidad abstraer un poco mas el componente de loading y armar un componente re utilizable en toda la solución, nos daria mayor mantenibilidad

2019-07-06 22:17 UTC, ismaelpuricelli commented on src/components/conversations.jsx
>            <LoadingScreen
Hecho!

2019-07-07 00:53 UTC, CamiloNicolasMartinez approved these changes

2019-07-07 18:59 UTC, juan17rodriguez approved these changes

2019-07-07 19:09 UTC, juan17rodriguez approved these changes

2019-07-08 18:38 UTC, agustico13 approved these changes

2019-07-08 22:47 UTC, merged