Refactor individual offer
coopify/coopify-frontend pull request #50
Opened 2019-07-04 23:12 UTC by agustico13

2019-07-05 17:01 UTC, CamiloNicolasMartinez commented on package.json
> +    "slick-carousel": "^1.8.1",
Esta bien que tengamos instaladas 2 librerias si solo incluimos el carrusel?

2019-07-05 17:02 UTC, CamiloNicolasMartinez commented on package.json
> +    "slick-carousel": "^1.8.1",
Del `slick-carousel` solo se usan los css, está bien q esté acá aun?

2019-07-05 17:03 UTC, CamiloNicolasMartinez requested changes
Confirmar que son necesarias las 2 librerias agregadas en este PR

2019-07-05 17:10 UTC, agustico13 commented on package.json
> +    "slick-carousel": "^1.8.1",
Instale las 2 porque así lo detalla la doc del componente.

https://www.npmjs.com/package/react-slick

Recuerdo que al principio instale solo la primera y no andaba bien.

2019-07-08 02:42 UTC, ismaelpuricelli approved these changes
Good work!

2019-07-08 15:41 UTC, juan17rodriguez approved these changes

2019-07-08 18:45 UTC, CamiloNicolasMartinez approved these changes

2019-07-08 22:38 UTC, merged